version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 677276091463.dkr.ecr.ap-northeast-1.amazonaws.com)
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t webapp .
      - docker tag webapp:latest 677276091463.dkr.ecr.ap-northeast-1.amazonaws.com/webapp:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 677276091463.dkr.ecr.ap-northeast-1.amazonaws.com/webapp:latest
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
